name: booktickets
description: A fully functional flight booking Flutter app with Paystack payments and SERP API integration.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI packages
  cupertino_icons: ^1.0.2
  fluentui_icons: ^1.0.0
  gap: ^2.0.0
  get:

  # Barcode display (already in your file)
  barcode_widget: ^2.0.2

  # Networking for API calls
  http: ^1.2.1

  # Payment integration
  paystack_payment: ^1.0.5

  # JSON handling
  flutter_json_view: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
