name: Build Flutter Web to docs folder

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Clean
        run: flutter clean

      - name: Build web
        run: flutter build web --release --base-href /Build-Deploy-Flutter-Web-to-Root/

      - name: Add .nojekyll
        run: touch build/web/.nojekyll

      - name: Copy to docs folder
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r build/web/* docs/
          cp build/web/.nojekyll docs/ || true

      - name: Commit and push to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update web build for GitHub Pages"
          file_pattern: "docs/*"
