name: Deploy Flutter Web App to Root

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Enable web
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href /Build-Deploy-Flutter-Web-to-Root/

      - name: Copy build to root
        run: |
          rm -rf *
          cp -r build/web/* .

      - name: Commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy Flutter Web to root [skip ci]" || echo "No changes to commit"
          git push
