name: Build & Deploy Flutter Web to Root

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable web support
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      - name: Clean previous builds
        run: flutter clean

      - name: Build Flutter web
        run: flutter build web --release --base-href /Build-Deploy-Flutter-Web-to-Root/

      - name: Add .nojekyll to artifact
        run: cp .nojekyll build/web/.nojekyll || echo "nojekyll already present"

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
          enable_jekyll: false
          force_orphan: true
